Repository FIS2425/appointment-svc, pull requests merged in 2025-01, with the labels that each got.

#64 v1.1.0
  .env.example
  .github/renovate.json
  .github/workflows/api-doc.yml
  .github/workflows/docker-deploy.yml
  .github/workflows/trigger-kubernetes-sync.yml
  Dockerfile
  docker-compose.yml
  kubernetes/appointment-deployment.yaml
  kubernetes/dragonfly-deployment.yaml
  kubernetes/dragonfly-service.yaml
  kubernetes/mongodb-deployment.yaml
  kubernetes/mongodb-service.yaml
  kubernetes/rabbitmq-deployment.yaml
  kubernetes/rabbitmq-service.yaml
  openapi.md
  openapi.yaml
  package-lock.json
  package.json
  populators/Appointment.js
  populators/runPopulator.js
  src/api.js
  src/controllers/appointmentController.js
  src/middleware/verifyAuth.js
  src/schemas/Appointment.js
  src/utils/kafkaTransport.js
  tests/integration/controllers/appointmentController.test.js
  tests/integration/controllers/dummy
  tests/integration/middleware/dummy
  tests/integration/middleware/verifyAuth.test.js
  tests/integration/routes/dummy
  tests/integration/schemas/Appointment.test.js
  tests/integration/utils/testData.js
  tests/setup/setup.js
  tests/unit/controllers/appointmentController.test.js
  tests/unit/middleware/verifyAuth.test.js
Labels: 🧪 Tests, 🤯 size/xl, ⚙️ Configuration, 📦 Dependencies, 🚀 CI/CD, 🐳 Build

#65 v1.1.1
  populators/Appointment.js
Labels: size/xs

#66 v1.1.2
  populators/Appointment.js
Labels: size/s

#67 v1.1.3
  src/api.js
  src/config/logger.js
  src/middleware/verifyAuth.js
  src/utils/kafkaTransport.js
  tests/integration/middleware/verifyAuth.test.js
  tests/integration/utils/testData.js
  tests/unit/middleware/verifyAuth.test.js
Labels: 🧪 Tests, 😎 size/m

#68 feat: fetch clinic data for weather forecast
  .env.example
  docker-compose.yml
  src/controllers/appointmentController.js
  src/utils/clinic.js
  src/utils/weather.js
Labels: ⚙️ Configuration, 🐳 Build, size/s

#79 v1.3.2
  populators/Appointment.js
Labels: size/xs
